### ISSUE TITLE
Add PDOK (WFS) API to NLX network

### ISSUE THREAD

**Issue by ehotting** [VNG-Realisatie/field-lab#40]

**Comment by ehotting** [comment]
In track 2 a BAG map is useful for the BLITSS app.
- [ ] What is the exact requirement?
- [ ] Can we add the right API to NLX network?

**Comment by ehotting** [comment]
Please redefine user story as required

**Comment by jgortmaker1** [comment]
BAG map ==> cadastral map
https://www.pdok.nl/nl/service/wfs-kadastrale-kaart-v3 zie ook: http://www.nationaalgeoregister.nl/geonetwork/srv/dut/catalog.search#/metadata/8bab07ea-6f4c-4583-9f31-9e4fe4b00d9f?tab=general

**Comment by ehotting** [comment]
Added to the NLX online demo, as can be seen here: https://directory.demo.nlx.io

**Comment by jgortmaker1** [comment]
api doumentation seems to indicate the pdok service is not the pdok map service from the comments above??
