### ISSUE TITLE
As NLX owner I want an emulation of VNG RGBZ API's online

### ISSUE THREAD

**Issue by ehotting** [VNG-Realisatie/field-lab#50]
Prepare
- [ ] register new domain
- [ ] host zakenmagazijn.demo.[new domain] on k8s (= haarlem-zaakmagazijn.maykin.nl )

Register in nlx.io directory
- [ ] with more realistic API name (“zaken”?)
- [ ] as organisation “VNG Realisatie” (includes new cert)

**Comment by joeribekker** [comment]
See #59
